version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    container_name: redis
    image: 'redis:latest'

  api:
    container_name: api
    build: 
      context: ./server
      dockerfile: Dockerfile.dev 
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password

    depends_on:
      - postgres
  client:
    stdin_open: true
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    container_name: nginx
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context:  ./nginx
    ports:
      - "3050:80"
        #    depends_on:
        #       - client
        #       - api
